Add a Book Builder class
RubiconDeFi/gladius-sdk pull request #2
Opened 2023-11-15 04:23 UTC by bghughes

The goal of this class is to provide a ready-to-use object that **makes it easy to track open orders for any given ERC20/ERC20 Gladius book**

Two features not yet added, that should be added:
- [ ] Lead-up time. An additional deadline filter where orders that are Date.now() + LeadUpTime away are not considered. This is a consideration for users who may need to, for instance, offer aggregator quotes to users that must be valid for LeadUpTime seconds into the feature. Should default to 0.
- [ ] Market Buy and Market Sell helper functions. These functions should return the exact data required to execute a market buy or sell into any given book the BookBuilder is watching. Importantly, these methods must adhere to the **no partial fills** condition of Gladius

2023-11-15 04:25 UTC, bghughes commented
Another feature for future improvement:
- [ ]  Add a feature that periodically uses `multicall` to batch check outstanding orders in the BookBuilder and automatically remove those that may have become in-`valid` in normal course of action

2023-11-16 01:57 UTC, bghughes reviewed
Ready to go from my eyes

2023-11-16 04:13 UTC, etherealiska requested changes

2023-11-16 04:31 UTC, bghughes commented on src/utils/BookBuilder.ts
> +    public async getOffers(): Promise<{ bids: any; asks: any }> {
There isn't a type already for this one... you're totally right though...

2023-11-16 04:31 UTC, bghughes commented on src/utils/BookBuilder.ts
> +    public async getOffers(): Promise<{ bids: any; asks: any }> {
worth noting it is only used internally 😅

2023-11-16 04:31 UTC, bghughes commented on src/utils/BookBuilder.ts
> +    public async getOffers(): Promise<{ bids: any; asks: any }> {
like most users will just `getBook`

2023-11-16 04:47 UTC, merged